export const CURRENCIES = {
  AED: {
    country: 'United Arab Emirates',
    symbol: 'AED',
    flag: '🇦🇪',
    sign: 'د.إ',
    num: '784',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  AFN: {
    country: 'Afghanistan',
    symbol: 'AFN',
    flag: '🇦🇫',
    sign: '؋',
    num: '971',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  ALL: {
    country: 'Albania',
    symbol: 'ALL',
    flag: '🇦🇱',
    sign: 'L',
    num: '008',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '039',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  AMD: {
    country: 'Armenia',
    symbol: 'AMD',
    flag: '🇦🇲',
    sign: '֏',
    num: '051',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  AOA: {
    country: 'Angola',
    symbol: 'AOA',
    flag: '🇦🇴',
    sign: 'Kz',
    num: '973',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '017',
      businessRegion: 'emea',
    },
  },
  ARS: {
    country: 'Argentina',
    symbol: 'ARS',
    flag: '🇦🇷',
    sign: '$',
    num: '032',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  AUD: {
    country: 'Australia',
    symbol: 'AUD',
    flag: '🇦🇺',
    sign: '$',
    num: '036',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '053',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  AWG: {
    country: 'Aruba',
    symbol: 'AWG',
    flag: '🇦🇼',
    sign: 'ƒ',
    num: '533',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  AZN: {
    country: 'Azerbaijan',
    symbol: 'AZN',
    flag: '🇦🇿',
    sign: '₼',
    num: '944',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  BAM: {
    country: 'Bosnia and Herzegovina',
    symbol: 'BAM',
    flag: '🇧🇦',
    sign: 'KM',
    num: '977',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '039',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  BBD: {
    country: 'Barbados',
    symbol: 'BBD',
    flag: '🇧🇧',
    sign: '$',
    num: '052',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  BDT: {
    country: 'Bangladesh',
    symbol: 'BDT',
    flag: '🇧🇩',
    sign: '৳',
    num: '050',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  BHD: {
    country: 'Bahrain',
    symbol: 'BHD',
    flag: '🇧🇭',
    sign: 'د.ب',
    num: '048',
    d: 3,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  BIF: {
    country: 'Burundi',
    symbol: 'BIF',
    flag: '🇧🇮',
    sign: 'FBu',
    num: '108',
    d: 0,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  BMD: {
    country: 'Bermuda',
    symbol: 'BMD',
    flag: '🇧🇲',
    sign: '$',
    num: '060',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '021',
      intermediateRegionCode: null,
      businessRegion: 'amer',
    },
  },
  BND: {
    country: 'Brunei Darussalam',
    symbol: 'BND',
    flag: '🇧🇳',
    sign: '$',
    num: '096',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  BOB: {
    country: 'Bolivia, Plurinational State of',
    symbol: 'BOB',
    flag: '🇧🇴',
    sign: 'Bs',
    num: '068',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  BRL: {
    country: 'Brazil',
    symbol: 'BRL',
    flag: '🇧🇷',
    sign: 'R$',
    num: '986',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  BSD: {
    country: 'Bahamas',
    symbol: 'BSD',
    flag: '🇧🇸',
    sign: '$',
    num: '044',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  BTN: {
    country: 'Bhutan',
    symbol: 'BTN',
    flag: '🇧🇹',
    sign: 'Nu.',
    num: '064',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  BWP: {
    country: 'Botswana',
    symbol: 'BWP',
    flag: '🇧🇼',
    sign: 'P',
    num: '072',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '018',
      businessRegion: 'emea',
    },
  },
  BYN: {
    country: 'Belarus',
    symbol: 'BYN',
    flag: '🇧🇾',
    sign: 'Br',
    num: '933',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  BZD: {
    country: 'Belize',
    symbol: 'BZD',
    flag: '🇧🇿',
    sign: '$',
    num: '084',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  CAD: {
    country: 'Canada',
    symbol: 'CAD',
    flag: '🇨🇦',
    sign: '$',
    num: '124',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '021',
      intermediateRegionCode: null,
      businessRegion: 'amer',
    },
  },
  CDF: {
    country: 'Congo, The Democratic Republic of the',
    symbol: 'CDF',
    flag: '🇨🇩',
    sign: 'FC',
    num: '976',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '017',
      businessRegion: 'emea',
    },
  },
  CHF: {
    country: 'Switzerland',
    symbol: 'CHF',
    flag: '🇨🇭',
    sign: 'Fr',
    num: '756',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '155',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  CLP: {
    country: 'Chile',
    symbol: 'CLP',
    flag: '🇨🇱',
    sign: '$',
    num: '152',
    d: 0,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  CNY: {
    country: 'China',
    symbol: 'CNY',
    flag: '🇨🇳',
    sign: '¥',
    num: '156',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  COP: {
    country: 'Colombia',
    symbol: 'COP',
    flag: '🇨🇴',
    sign: '$',
    num: '170',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  CRC: {
    country: 'Costa Rica',
    symbol: 'CRC',
    flag: '🇨🇷',
    sign: '₡',
    num: '188',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  CVE: {
    country: 'Cabo Verde',
    symbol: 'CVE',
    flag: '🇨🇻',
    sign: 'Esc',
    num: '132',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  CZK: {
    country: 'Czechia',
    symbol: 'CZK',
    flag: '🇨🇿',
    sign: 'Kč',
    num: '203',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  DJF: {
    country: 'Djibouti',
    symbol: 'DJF',
    flag: '🇩🇯',
    sign: 'Fdj',
    num: '262',
    d: 0,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  DKK: {
    country: 'Denmark',
    symbol: 'DKK',
    flag: '🇩🇰',
    sign: 'kr',
    num: '208',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '154',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  DOP: {
    country: 'Dominican Republic',
    symbol: 'DOP',
    flag: '🇩🇴',
    sign: 'RD$',
    num: '214',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  DZD: {
    country: 'Algeria',
    symbol: 'DZD',
    flag: '🇩🇿',
    sign: 'د.ج',
    num: '012',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '015',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  EGP: {
    country: 'Egypt',
    symbol: 'EGP',
    flag: '🇪🇬',
    sign: '£',
    num: '818',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '015',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  ERN: {
    country: 'Eritrea',
    symbol: 'ERN',
    flag: '🇪🇷',
    sign: 'Nkf',
    num: '232',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  ETB: {
    country: 'Ethiopia',
    symbol: 'ETB',
    flag: '🇪🇹',
    sign: 'Br',
    num: '230',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  EUR: {
    country: 'European Union',
    symbol: 'EUR',
    flag: '🇪🇺',
    sign: '€',
    num: '978',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: null,
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  FJD: {
    country: 'Fiji',
    symbol: 'FJD',
    flag: '🇫🇯',
    sign: '$',
    num: '242',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '054',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  FKP: {
    country: 'Falkland Islands (Malvinas)',
    symbol: 'FKP',
    flag: '🇫🇰',
    sign: '£',
    num: '238',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  GBP: {
    country: 'United Kingdom',
    symbol: 'GBP',
    flag: '🇬🇧',
    sign: '£',
    num: '826',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '154',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  GEL: {
    country: 'Georgia',
    symbol: 'GEL',
    flag: '🇬🇪',
    sign: '₾',
    num: '981',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  GHS: {
    country: 'Ghana',
    symbol: 'GHS',
    flag: '🇬🇭',
    sign: '₵',
    num: '936',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  GIP: {
    country: 'Gibraltar',
    symbol: 'GIP',
    flag: '🇬🇮',
    sign: '£',
    num: '292',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '039',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  GMD: {
    country: 'Gambia',
    symbol: 'GMD',
    flag: '🇬🇲',
    sign: 'D',
    num: '270',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  GNF: {
    country: 'Guinea',
    symbol: 'GNF',
    flag: '🇬🇳',
    sign: 'FG',
    num: '324',
    d: 0,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  GTQ: {
    country: 'Guatemala',
    symbol: 'GTQ',
    flag: '🇬🇹',
    sign: 'Q',
    num: '320',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  GYD: {
    country: 'Guyana',
    symbol: 'GYD',
    flag: '🇬🇾',
    sign: '$',
    num: '328',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  HKD: {
    country: 'Hong Kong',
    symbol: 'HKD',
    flag: '🇭🇰',
    sign: '$',
    num: '344',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  HNL: {
    country: 'Honduras',
    symbol: 'HNL',
    flag: '🇭🇳',
    sign: 'L',
    num: '340',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  HTG: {
    country: 'Haiti',
    symbol: 'HTG',
    flag: '🇭🇹',
    sign: 'G',
    num: '332',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  HUF: {
    country: 'Hungary',
    symbol: 'HUF',
    flag: '🇭🇺',
    sign: 'Ft',
    num: '348',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  IDR: {
    country: 'Indonesia',
    symbol: 'IDR',
    flag: '🇮🇩',
    sign: 'Rp',
    num: '360',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  ILS: {
    country: 'Israel',
    symbol: 'ILS',
    flag: '🇮🇱',
    sign: '₪',
    num: '376',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  INR: {
    country: 'India',
    symbol: 'INR',
    flag: '🇮🇳',
    sign: '₹',
    num: '356',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  IQD: {
    country: 'Iraq',
    symbol: 'IQD',
    flag: '🇮🇶',
    sign: 'ع.د',
    num: '368',
    d: 3,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  IRR: {
    country: 'Iran',
    symbol: 'IRR',
    flag: '🇮🇷',
    sign: '﷼',
    num: '364',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  ISK: {
    country: 'Iceland',
    symbol: 'ISK',
    flag: '🇮🇸',
    sign: 'kr',
    num: '352',
    d: 0,
    region: {
      regionCode: '150',
      subregionCode: '154',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  JMD: {
    country: 'Jamaica',
    symbol: 'JMD',
    flag: '🇯🇲',
    sign: '$',
    num: '388',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  JOD: {
    country: 'Jordan',
    symbol: 'JOD',
    flag: '🇯🇴',
    sign: 'د.أ',
    num: '400',
    d: 3,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  JPY: {
    country: 'Japan',
    symbol: 'JPY',
    flag: '🇯🇵',
    sign: '¥',
    num: '392',
    d: 0,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  KES: {
    country: 'Kenya',
    symbol: 'KES',
    flag: '🇰🇪',
    sign: 'KSh',
    num: '404',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  KGS: {
    country: 'Kyrgyzstan',
    symbol: 'KGS',
    flag: '🇰🇬',
    sign: '⃀',
    num: '417',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '143',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  KHR: {
    country: 'Cambodia',
    symbol: 'KHR',
    flag: '🇰🇭',
    sign: '៛',
    num: '116',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  KMF: {
    country: 'Comoros',
    symbol: 'KMF',
    flag: '🇰🇲',
    sign: 'Fr',
    num: '174',
    d: 0,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  KPW: {
    country: 'North Korea',
    symbol: 'KPW',
    flag: '🇰🇵',
    sign: '₩',
    num: '408',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  KRW: {
    country: 'South Korea',
    symbol: 'KRW',
    flag: '🇰🇷',
    sign: '₩',
    num: '410',
    d: 0,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  KWD: {
    country: 'Kuwait',
    symbol: 'KWD',
    flag: '🇰🇼',
    sign: 'د.ك',
    num: '414',
    d: 3,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  KYD: {
    country: 'Cayman Islands',
    symbol: 'KYD',
    flag: '🇰🇾',
    sign: '$',
    num: '136',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  KZT: {
    country: 'Kazakhstan',
    symbol: 'KZT',
    flag: '🇰🇿',
    sign: '₸',
    num: '398',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '143',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  LAK: {
    country: 'Laos',
    symbol: 'LAK',
    flag: '🇱🇦',
    sign: '₭',
    num: '418',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  LBP: {
    country: 'Lebanon',
    symbol: 'LBP',
    flag: '🇱🇧',
    sign: 'ل.ل',
    num: '422',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  LKR: {
    country: 'Sri Lanka',
    symbol: 'LKR',
    flag: '🇱🇰',
    sign: 'Rs',
    num: '144',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  LRD: {
    country: 'Liberia',
    symbol: 'LRD',
    flag: '🇱🇷',
    sign: '$',
    num: '430',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  LSL: {
    country: 'Lesotho',
    symbol: 'LSL',
    flag: '🇱🇸',
    sign: 'L',
    num: '426',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '018',
      businessRegion: 'emea',
    },
  },
  LYD: {
    country: 'Libya',
    symbol: 'LYD',
    flag: '🇱🇾',
    sign: 'ل.د',
    num: '434',
    d: 3,
    region: {
      regionCode: '002',
      subregionCode: '015',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  MAD: {
    country: 'Morocco',
    symbol: 'MAD',
    flag: '🇲🇦',
    sign: 'د.م.',
    num: '504',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '015',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  MDL: {
    country: 'Moldova',
    symbol: 'MDL',
    flag: '🇲🇩',
    sign: 'L',
    num: '498',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  MGA: {
    country: 'Madagascar',
    symbol: 'MGA',
    flag: '🇲🇬',
    sign: 'Ar',
    num: '969',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  MKD: {
    country: 'North Macedonia',
    symbol: 'MKD',
    flag: '🇲🇰',
    sign: 'ден',
    num: '807',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '039',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  MMK: {
    country: 'Myanmar',
    symbol: 'MMK',
    flag: '🇲🇲',
    sign: 'K',
    num: '104',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  MNT: {
    country: 'Mongolia',
    symbol: 'MNT',
    flag: '🇲🇳',
    sign: '₮',
    num: '496',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  MOP: {
    country: 'Macao',
    symbol: 'MOP',
    flag: '🇲🇴',
    sign: 'MOP$',
    num: '446',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  MUR: {
    country: 'Mauritius',
    symbol: 'MUR',
    flag: '🇲🇺',
    sign: '₨',
    num: '480',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  MVR: {
    country: 'Maldives',
    symbol: 'MVR',
    flag: '🇲🇻',
    sign: 'Rf',
    num: '462',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  MWK: {
    country: 'Malawi',
    symbol: 'MWK',
    flag: '🇲🇼',
    sign: 'MK',
    num: '454',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  MXN: {
    country: 'Mexico',
    symbol: 'MXN',
    flag: '🇲🇽',
    sign: '$',
    num: '484',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  MYR: {
    country: 'Malaysia',
    symbol: 'MYR',
    flag: '🇲🇾',
    sign: 'RM',
    num: '458',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  MZN: {
    country: 'Mozambique',
    symbol: 'MZN',
    flag: '🇲🇿',
    sign: 'MT',
    num: '943',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  NAD: {
    country: 'Namibia',
    symbol: 'NAD',
    flag: '🇳🇦',
    sign: '$',
    num: '516',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '018',
      businessRegion: 'emea',
    },
  },
  NGN: {
    country: 'Nigeria',
    symbol: 'NGN',
    flag: '🇳🇬',
    sign: '₦',
    num: '566',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  NIO: {
    country: 'Nicaragua',
    symbol: 'NIO',
    flag: '🇳🇮',
    sign: 'C$',
    num: '558',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  NOK: {
    country: 'Norway',
    symbol: 'NOK',
    flag: '🇳🇴',
    sign: 'kr',
    num: '578',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '154',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  NPR: {
    country: 'Nepal',
    symbol: 'NPR',
    flag: '🇳🇵',
    sign: '₨',
    num: '524',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  NZD: {
    country: 'New Zealand',
    symbol: 'NZD',
    flag: '🇳🇿',
    sign: '$',
    num: '554',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '053',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  OMR: {
    country: 'Oman',
    symbol: 'OMR',
    flag: '🇴🇲',
    sign: 'ر.ع.',
    num: '512',
    d: 3,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  PAB: {
    country: 'Panama',
    symbol: 'PAB',
    flag: '🇵🇦',
    sign: 'B/.',
    num: '590',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  PEN: {
    country: 'Peru',
    symbol: 'PEN',
    flag: '🇵🇪',
    sign: 'S/',
    num: '604',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  PGK: {
    country: 'Papua New Guinea',
    symbol: 'PGK',
    flag: '🇵🇬',
    sign: 'K',
    num: '598',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '054',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  PHP: {
    country: 'Philippines',
    symbol: 'PHP',
    flag: '🇵🇭',
    sign: '₱',
    num: '608',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  PKR: {
    country: 'Pakistan',
    symbol: 'PKR',
    flag: '🇵🇰',
    sign: '₨',
    num: '586',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '034',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  PLN: {
    country: 'Poland',
    symbol: 'PLN',
    flag: '🇵🇱',
    sign: 'zł',
    num: '985',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  PYG: {
    country: 'Paraguay',
    symbol: 'PYG',
    flag: '🇵🇾',
    sign: '₲',
    num: '600',
    d: 0,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  QAR: {
    country: 'Qatar',
    symbol: 'QAR',
    flag: '🇶🇦',
    sign: 'ر.ق',
    num: '634',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  RON: {
    country: 'Romania',
    symbol: 'RON',
    flag: '🇷🇴',
    sign: 'lei',
    num: '946',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  RSD: {
    country: 'Serbia',
    symbol: 'RSD',
    flag: '🇷🇸',
    sign: 'дин',
    num: '941',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '039',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  RUB: {
    country: 'Russian Federation',
    symbol: 'RUB',
    flag: '🇷🇺',
    sign: '₽',
    num: '643',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  RWF: {
    country: 'Rwanda',
    symbol: 'RWF',
    flag: '🇷🇼',
    sign: 'Fr',
    num: '646',
    d: 0,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  SAR: {
    country: 'Saudi Arabia',
    symbol: 'SAR',
    flag: '🇸🇦',
    sign: 'ر.س',
    num: '682',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  SBD: {
    country: 'Solomon Islands',
    symbol: 'SBD',
    flag: '🇸🇧',
    sign: '$',
    num: '090',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '054',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  SCR: {
    country: 'Seychelles',
    symbol: 'SCR',
    flag: '🇸🇨',
    sign: '₨',
    num: '690',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  SDG: {
    country: 'Sudan',
    symbol: 'SDG',
    flag: '🇸🇩',
    sign: '£',
    num: '938',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '015',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  SEK: {
    country: 'Sweden',
    symbol: 'SEK',
    flag: '🇸🇪',
    sign: 'kr',
    num: '752',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '154',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  SGD: {
    country: 'Singapore',
    symbol: 'SGD',
    flag: '🇸🇬',
    sign: '$',
    num: '702',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  SHP: {
    country: 'Saint Helena',
    symbol: 'SHP',
    flag: '🇸🇭',
    sign: '£',
    num: '654',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '011',
      businessRegion: 'emea',
    },
  },
  SOS: {
    country: 'Somalia',
    symbol: 'SOS',
    flag: '🇸🇴',
    sign: 'Sh',
    num: '706',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  SRD: {
    country: 'Suriname',
    symbol: 'SRD',
    flag: '🇸🇷',
    sign: '$',
    num: '968',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  SSP: {
    country: 'South Sudan',
    symbol: 'SSP',
    flag: '🇸🇸',
    sign: '£',
    num: '728',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  SVC: {
    country: 'El Salvador',
    symbol: 'SVC',
    flag: '🇸🇻',
    sign: '₡',
    num: '222',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '013',
      businessRegion: 'latam',
    },
  },
  SYP: {
    country: 'Syrian Arab Republic',
    symbol: 'SYP',
    flag: '🇸🇾',
    sign: '£',
    num: '760',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  SZL: {
    country: 'Eswatini',
    symbol: 'SZL',
    flag: '🇸🇿',
    sign: 'L',
    num: '748',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '018',
      businessRegion: 'emea',
    },
  },
  THB: {
    country: 'Thailand',
    symbol: 'THB',
    flag: '🇹🇭',
    sign: '฿',
    num: '764',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  TJS: {
    country: 'Tajikistan',
    symbol: 'TJS',
    flag: '🇹🇯',
    sign: 'ЅМ',
    num: '972',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '143',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  TMT: {
    country: 'Turkmenistan',
    symbol: 'TMT',
    flag: '🇹🇲',
    sign: 'm',
    num: '934',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '143',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  TND: {
    country: 'Tunisia',
    symbol: 'TND',
    flag: '🇹🇳',
    sign: 'د.ت',
    num: '788',
    d: 3,
    region: {
      regionCode: '002',
      subregionCode: '015',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  TOP: {
    country: 'Tonga',
    symbol: 'TOP',
    flag: '🇹🇴',
    sign: 'T$',
    num: '776',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '061',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  TRY: {
    country: 'Turkey',
    symbol: 'TRY',
    flag: '🇹🇷',
    sign: '₺',
    num: '949',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  TTD: {
    country: 'Trinidad and Tobago',
    symbol: 'TTD',
    flag: '🇹🇹',
    sign: '$',
    num: '780',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '029',
      businessRegion: 'latam',
    },
  },
  TWD: {
    country: 'Taiwan',
    symbol: 'TWD',
    flag: '🇹🇼',
    sign: 'NT$',
    num: '901',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '030',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  TZS: {
    country: 'Tanzania',
    symbol: 'TZS',
    flag: '🇹🇿',
    sign: 'TSh',
    num: '834',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  UAH: {
    country: 'Ukraine',
    symbol: 'UAH',
    flag: '🇺🇦',
    sign: '₴',
    num: '980',
    d: 2,
    region: {
      regionCode: '150',
      subregionCode: '151',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  UGX: {
    country: 'Uganda',
    symbol: 'UGX',
    flag: '🇺🇬',
    sign: 'USh',
    num: '800',
    d: 0,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
  USD: {
    country: 'United States',
    symbol: 'USD',
    flag: '🇺🇸',
    sign: '$',
    num: '840',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '021',
      intermediateRegionCode: null,
      businessRegion: 'amer',
    },
  },
  UYU: {
    country: 'Uruguay',
    symbol: 'UYU',
    flag: '🇺🇾',
    sign: '$U',
    num: '858',
    d: 2,
    region: {
      regionCode: '019',
      subregionCode: '419',
      intermediateRegionCode: '005',
      businessRegion: 'latam',
    },
  },
  UZS: {
    country: 'Uzbekistan',
    symbol: 'UZS',
    flag: '🇺🇿',
    sign: "so'm",
    num: '860',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '143',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  VND: {
    country: 'Vietnam',
    symbol: 'VND',
    flag: '🇻🇳',
    sign: '₫',
    num: '704',
    d: 0,
    region: {
      regionCode: '142',
      subregionCode: '035',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  VUV: {
    country: 'Vanuatu',
    symbol: 'VUV',
    flag: '🇻🇺',
    sign: 'VT',
    num: '548',
    d: 0,
    region: {
      regionCode: '009',
      subregionCode: '054',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  WST: {
    country: 'Samoa',
    symbol: 'WST',
    flag: '🇼🇸',
    sign: 'WS$',
    num: '882',
    d: 2,
    region: {
      regionCode: '009',
      subregionCode: '061',
      intermediateRegionCode: null,
      businessRegion: 'apac',
    },
  },
  YER: {
    country: 'Yemen',
    symbol: 'YER',
    flag: '🇾🇪',
    sign: '﷼',
    num: '886',
    d: 2,
    region: {
      regionCode: '142',
      subregionCode: '145',
      intermediateRegionCode: null,
      businessRegion: 'emea',
    },
  },
  ZAR: {
    country: 'South Africa',
    symbol: 'ZAR',
    flag: '🇿🇦',
    sign: 'R',
    num: '710',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '018',
      businessRegion: 'emea',
    },
  },
  ZMW: {
    country: 'Zambia',
    symbol: 'ZMW',
    flag: '🇿🇲',
    sign: 'ZK',
    num: '967',
    d: 2,
    region: {
      regionCode: '002',
      subregionCode: '202',
      intermediateRegionCode: '014',
      businessRegion: 'emea',
    },
  },
} as const;
