import { ISO_4217_CURRENCIES } from '../iso4217/iso4217.js';
import {
  BUSINESS_REGIONS,
  M49_INTERMEDIATE_REGIONS,
  M49_REGIONS,
  M49_SUBREGIONS,
} from '../regions/regions.js';

export const CURRENCIES = {
  AED: {
    country: 'United Arab Emirates',
    symbol: 'AED',
    flag: '🇦🇪',
    sign: 'د.إ',
    num: String(ISO_4217_CURRENCIES['AED'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AED'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  AFN: {
    country: 'Afghanistan',
    symbol: 'AFN',
    flag: '🇦🇫',
    sign: '؋',
    num: String(ISO_4217_CURRENCIES['AFN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AFN'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  ALL: {
    country: 'Albania',
    symbol: 'ALL',
    flag: '🇦🇱',
    sign: 'L',
    num: String(ISO_4217_CURRENCIES['ALL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ALL'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['039'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  AMD: {
    country: 'Armenia',
    symbol: 'AMD',
    flag: '🇦🇲',
    sign: '֏',
    num: String(ISO_4217_CURRENCIES['AMD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AMD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  AOA: {
    country: 'Angola',
    symbol: 'AOA',
    flag: '🇦🇴',
    sign: 'Kz',
    num: String(ISO_4217_CURRENCIES['AOA'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AOA'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['017'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  ARS: {
    country: 'Argentina',
    symbol: 'ARS',
    flag: '🇦🇷',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['ARS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ARS'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  AUD: {
    country: 'Australia',
    symbol: 'AUD',
    flag: '🇦🇺',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['AUD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AUD'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['053'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  AWG: {
    country: 'Aruba',
    symbol: 'AWG',
    flag: '🇦🇼',
    sign: 'ƒ',
    num: String(ISO_4217_CURRENCIES['AWG'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AWG'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  AZN: {
    country: 'Azerbaijan',
    symbol: 'AZN',
    flag: '🇦🇿',
    sign: '₼',
    num: String(ISO_4217_CURRENCIES['AZN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['AZN'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  BAM: {
    country: 'Bosnia and Herzegovina',
    symbol: 'BAM',
    flag: '🇧🇦',
    sign: 'KM',
    num: String(ISO_4217_CURRENCIES['BAM'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BAM'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['039'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  BBD: {
    country: 'Barbados',
    symbol: 'BBD',
    flag: '🇧🇧',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['BBD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BBD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  BDT: {
    country: 'Bangladesh',
    symbol: 'BDT',
    flag: '🇧🇩',
    sign: '৳',
    num: String(ISO_4217_CURRENCIES['BDT'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BDT'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  BHD: {
    country: 'Bahrain',
    symbol: 'BHD',
    flag: '🇧🇭',
    sign: 'د.ب',
    num: String(ISO_4217_CURRENCIES['BHD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BHD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  BIF: {
    country: 'Burundi',
    symbol: 'BIF',
    flag: '🇧🇮',
    sign: 'FBu',
    num: String(ISO_4217_CURRENCIES['BIF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BIF'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  BMD: {
    country: 'Bermuda',
    symbol: 'BMD',
    flag: '🇧🇲',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['BMD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BMD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['021'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[2],
    },
  },
  BND: {
    country: 'Brunei Darussalam',
    symbol: 'BND',
    flag: '🇧🇳',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['BND'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BND'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  BOB: {
    country: 'Bolivia, Plurinational State of',
    symbol: 'BOB',
    flag: '🇧🇴',
    sign: 'Bs',
    num: String(ISO_4217_CURRENCIES['BOB'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BOB'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  BRL: {
    country: 'Brazil',
    symbol: 'BRL',
    flag: '🇧🇷',
    sign: 'R$',
    num: String(ISO_4217_CURRENCIES['BRL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BRL'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  BSD: {
    country: 'Bahamas',
    symbol: 'BSD',
    flag: '🇧🇸',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['BSD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BSD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  BTN: {
    country: 'Bhutan',
    symbol: 'BTN',
    flag: '🇧🇹',
    sign: 'Nu.',
    num: String(ISO_4217_CURRENCIES['BTN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BTN'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  BWP: {
    country: 'Botswana',
    symbol: 'BWP',
    flag: '🇧🇼',
    sign: 'P',
    num: String(ISO_4217_CURRENCIES['BWP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BWP'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['018'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  BYN: {
    country: 'Belarus',
    symbol: 'BYN',
    flag: '🇧🇾',
    sign: 'Br',
    num: String(ISO_4217_CURRENCIES['BYN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BYN'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  BZD: {
    country: 'Belize',
    symbol: 'BZD',
    flag: '🇧🇿',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['BZD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['BZD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  CAD: {
    country: 'Canada',
    symbol: 'CAD',
    flag: '🇨🇦',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['CAD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CAD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['021'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[2],
    },
  },
  CDF: {
    country: 'Congo, The Democratic Republic of the',
    symbol: 'CDF',
    flag: '🇨🇩',
    sign: 'FC',
    num: String(ISO_4217_CURRENCIES['CDF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CDF'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['017'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  CHF: {
    country: 'Switzerland',
    symbol: 'CHF',
    flag: '🇨🇭',
    sign: 'Fr',
    num: String(ISO_4217_CURRENCIES['CHF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CHF'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['155'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  CLP: {
    country: 'Chile',
    symbol: 'CLP',
    flag: '🇨🇱',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['CLP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CLP'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  CNY: {
    country: 'China',
    symbol: 'CNY',
    flag: '🇨🇳',
    sign: '¥',
    num: String(ISO_4217_CURRENCIES['CNY'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CNY'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  COP: {
    country: 'Colombia',
    symbol: 'COP',
    flag: '🇨🇴',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['COP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['COP'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  CRC: {
    country: 'Costa Rica',
    symbol: 'CRC',
    flag: '🇨🇷',
    sign: '₡',
    num: String(ISO_4217_CURRENCIES['CRC'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CRC'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  CVE: {
    country: 'Cabo Verde',
    symbol: 'CVE',
    flag: '🇨🇻',
    sign: 'Esc',
    num: String(ISO_4217_CURRENCIES['CVE'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CVE'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  CZK: {
    country: 'Czechia',
    symbol: 'CZK',
    flag: '🇨🇿',
    sign: 'Kč',
    num: String(ISO_4217_CURRENCIES['CZK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['CZK'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  DJF: {
    country: 'Djibouti',
    symbol: 'DJF',
    flag: '🇩🇯',
    sign: 'Fdj',
    num: String(ISO_4217_CURRENCIES['DJF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['DJF'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  DKK: {
    country: 'Denmark',
    symbol: 'DKK',
    flag: '🇩🇰',
    sign: 'kr',
    num: String(ISO_4217_CURRENCIES['DKK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['DKK'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['154'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  DOP: {
    country: 'Dominican Republic',
    symbol: 'DOP',
    flag: '🇩🇴',
    sign: 'RD$',
    num: String(ISO_4217_CURRENCIES['DOP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['DOP'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  DZD: {
    country: 'Algeria',
    symbol: 'DZD',
    flag: '🇩🇿',
    sign: 'د.ج',
    num: String(ISO_4217_CURRENCIES['DZD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['DZD'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['015'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  EGP: {
    country: 'Egypt',
    symbol: 'EGP',
    flag: '🇪🇬',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['EGP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['EGP'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['015'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  ERN: {
    country: 'Eritrea',
    symbol: 'ERN',
    flag: '🇪🇷',
    sign: 'Nkf',
    num: String(ISO_4217_CURRENCIES['ERN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ERN'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  ETB: {
    country: 'Ethiopia',
    symbol: 'ETB',
    flag: '🇪🇹',
    sign: 'Br',
    num: String(ISO_4217_CURRENCIES['ETB'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ETB'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  EUR: {
    country: 'European Union',
    symbol: 'EUR',
    flag: '🇪🇺',
    sign: '€',
    num: String(ISO_4217_CURRENCIES['EUR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['EUR'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: null,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  FJD: {
    country: 'Fiji',
    symbol: 'FJD',
    flag: '🇫🇯',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['FJD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['FJD'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['054'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  FKP: {
    country: 'Falkland Islands (Malvinas)',
    symbol: 'FKP',
    flag: '🇫🇰',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['FKP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['FKP'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  GBP: {
    country: 'United Kingdom',
    symbol: 'GBP',
    flag: '🇬🇧',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['GBP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GBP'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['154'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  GEL: {
    country: 'Georgia',
    symbol: 'GEL',
    flag: '🇬🇪',
    sign: '₾',
    num: String(ISO_4217_CURRENCIES['GEL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GEL'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  GHS: {
    country: 'Ghana',
    symbol: 'GHS',
    flag: '🇬🇭',
    sign: '₵',
    num: String(ISO_4217_CURRENCIES['GHS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GHS'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  GIP: {
    country: 'Gibraltar',
    symbol: 'GIP',
    flag: '🇬🇮',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['GIP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GIP'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['039'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  GMD: {
    country: 'Gambia',
    symbol: 'GMD',
    flag: '🇬🇲',
    sign: 'D',
    num: String(ISO_4217_CURRENCIES['GMD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GMD'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  GNF: {
    country: 'Guinea',
    symbol: 'GNF',
    flag: '🇬🇳',
    sign: 'FG',
    num: String(ISO_4217_CURRENCIES['GNF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GNF'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  GTQ: {
    country: 'Guatemala',
    symbol: 'GTQ',
    flag: '🇬🇹',
    sign: 'Q',
    num: String(ISO_4217_CURRENCIES['GTQ'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GTQ'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  GYD: {
    country: 'Guyana',
    symbol: 'GYD',
    flag: '🇬🇾',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['GYD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['GYD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  HKD: {
    country: 'Hong Kong',
    symbol: 'HKD',
    flag: '🇭🇰',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['HKD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['HKD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  HNL: {
    country: 'Honduras',
    symbol: 'HNL',
    flag: '🇭🇳',
    sign: 'L',
    num: String(ISO_4217_CURRENCIES['HNL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['HNL'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  HTG: {
    country: 'Haiti',
    symbol: 'HTG',
    flag: '🇭🇹',
    sign: 'G',
    num: String(ISO_4217_CURRENCIES['HTG'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['HTG'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  HUF: {
    country: 'Hungary',
    symbol: 'HUF',
    flag: '🇭🇺',
    sign: 'Ft',
    num: String(ISO_4217_CURRENCIES['HUF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['HUF'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  IDR: {
    country: 'Indonesia',
    symbol: 'IDR',
    flag: '🇮🇩',
    sign: 'Rp',
    num: String(ISO_4217_CURRENCIES['IDR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['IDR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  ILS: {
    country: 'Israel',
    symbol: 'ILS',
    flag: '🇮🇱',
    sign: '₪',
    num: String(ISO_4217_CURRENCIES['ILS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ILS'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  INR: {
    country: 'India',
    symbol: 'INR',
    flag: '🇮🇳',
    sign: '₹',
    num: String(ISO_4217_CURRENCIES['INR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['INR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  IQD: {
    country: 'Iraq',
    symbol: 'IQD',
    flag: '🇮🇶',
    sign: 'ع.د',
    num: String(ISO_4217_CURRENCIES['IQD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['IQD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  IRR: {
    country: 'Iran',
    symbol: 'IRR',
    flag: '🇮🇷',
    sign: '﷼',
    num: String(ISO_4217_CURRENCIES['IRR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['IRR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  ISK: {
    country: 'Iceland',
    symbol: 'ISK',
    flag: '🇮🇸',
    sign: 'kr',
    num: String(ISO_4217_CURRENCIES['ISK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ISK'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['154'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  JMD: {
    country: 'Jamaica',
    symbol: 'JMD',
    flag: '🇯🇲',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['JMD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['JMD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  JOD: {
    country: 'Jordan',
    symbol: 'JOD',
    flag: '🇯🇴',
    sign: 'د.أ',
    num: String(ISO_4217_CURRENCIES['JOD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['JOD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  JPY: {
    country: 'Japan',
    symbol: 'JPY',
    flag: '🇯🇵',
    sign: '¥',
    num: String(ISO_4217_CURRENCIES['JPY'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['JPY'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  KES: {
    country: 'Kenya',
    symbol: 'KES',
    flag: '🇰🇪',
    sign: 'KSh',
    num: String(ISO_4217_CURRENCIES['KES'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KES'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  KGS: {
    country: 'Kyrgyzstan',
    symbol: 'KGS',
    flag: '🇰🇬',
    sign: '⃀',
    num: String(ISO_4217_CURRENCIES['KGS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KGS'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['143'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  KHR: {
    country: 'Cambodia',
    symbol: 'KHR',
    flag: '🇰🇭',
    sign: '៛',
    num: String(ISO_4217_CURRENCIES['KHR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KHR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  KMF: {
    country: 'Comoros',
    symbol: 'KMF',
    flag: '🇰🇲',
    sign: 'Fr',
    num: String(ISO_4217_CURRENCIES['KMF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KMF'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  KPW: {
    country: 'North Korea',
    symbol: 'KPW',
    flag: '🇰🇵',
    sign: '₩',
    num: String(ISO_4217_CURRENCIES['KPW'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KPW'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  KRW: {
    country: 'South Korea',
    symbol: 'KRW',
    flag: '🇰🇷',
    sign: '₩',
    num: String(ISO_4217_CURRENCIES['KRW'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KRW'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  KWD: {
    country: 'Kuwait',
    symbol: 'KWD',
    flag: '🇰🇼',
    sign: 'د.ك',
    num: String(ISO_4217_CURRENCIES['KWD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KWD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  KYD: {
    country: 'Cayman Islands',
    symbol: 'KYD',
    flag: '🇰🇾',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['KYD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KYD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  KZT: {
    country: 'Kazakhstan',
    symbol: 'KZT',
    flag: '🇰🇿',
    sign: '₸',
    num: String(ISO_4217_CURRENCIES['KZT'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['KZT'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['143'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  LAK: {
    country: 'Laos',
    symbol: 'LAK',
    flag: '🇱🇦',
    sign: '₭',
    num: String(ISO_4217_CURRENCIES['LAK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['LAK'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  LBP: {
    country: 'Lebanon',
    symbol: 'LBP',
    flag: '🇱🇧',
    sign: 'ل.ل',
    num: String(ISO_4217_CURRENCIES['LBP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['LBP'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  LKR: {
    country: 'Sri Lanka',
    symbol: 'LKR',
    flag: '🇱🇰',
    sign: 'Rs',
    num: String(ISO_4217_CURRENCIES['LKR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['LKR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  LRD: {
    country: 'Liberia',
    symbol: 'LRD',
    flag: '🇱🇷',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['LRD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['LRD'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  LSL: {
    country: 'Lesotho',
    symbol: 'LSL',
    flag: '🇱🇸',
    sign: 'L',
    num: String(ISO_4217_CURRENCIES['LSL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['LSL'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['018'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  LYD: {
    country: 'Libya',
    symbol: 'LYD',
    flag: '🇱🇾',
    sign: 'ل.د',
    num: String(ISO_4217_CURRENCIES['LYD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['LYD'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['015'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MAD: {
    country: 'Morocco',
    symbol: 'MAD',
    flag: '🇲🇦',
    sign: 'د.م.',
    num: String(ISO_4217_CURRENCIES['MAD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MAD'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['015'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MDL: {
    country: 'Moldova',
    symbol: 'MDL',
    flag: '🇲🇩',
    sign: 'L',
    num: String(ISO_4217_CURRENCIES['MDL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MDL'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MGA: {
    country: 'Madagascar',
    symbol: 'MGA',
    flag: '🇲🇬',
    sign: 'Ar',
    num: String(ISO_4217_CURRENCIES['MGA'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MGA'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MKD: {
    country: 'North Macedonia',
    symbol: 'MKD',
    flag: '🇲🇰',
    sign: 'ден',
    num: String(ISO_4217_CURRENCIES['MKD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MKD'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['039'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MMK: {
    country: 'Myanmar',
    symbol: 'MMK',
    flag: '🇲🇲',
    sign: 'K',
    num: String(ISO_4217_CURRENCIES['MMK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MMK'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  MNT: {
    country: 'Mongolia',
    symbol: 'MNT',
    flag: '🇲🇳',
    sign: '₮',
    num: String(ISO_4217_CURRENCIES['MNT'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MNT'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  MOP: {
    country: 'Macao',
    symbol: 'MOP',
    flag: '🇲🇴',
    sign: 'MOP$',
    num: String(ISO_4217_CURRENCIES['MOP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MOP'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  MUR: {
    country: 'Mauritius',
    symbol: 'MUR',
    flag: '🇲🇺',
    sign: '₨',
    num: String(ISO_4217_CURRENCIES['MUR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MUR'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MVR: {
    country: 'Maldives',
    symbol: 'MVR',
    flag: '🇲🇻',
    sign: 'Rf',
    num: String(ISO_4217_CURRENCIES['MVR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MVR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  MWK: {
    country: 'Malawi',
    symbol: 'MWK',
    flag: '🇲🇼',
    sign: 'MK',
    num: String(ISO_4217_CURRENCIES['MWK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MWK'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  MXN: {
    country: 'Mexico',
    symbol: 'MXN',
    flag: '🇲🇽',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['MXN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MXN'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  MYR: {
    country: 'Malaysia',
    symbol: 'MYR',
    flag: '🇲🇾',
    sign: 'RM',
    num: String(ISO_4217_CURRENCIES['MYR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MYR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  MZN: {
    country: 'Mozambique',
    symbol: 'MZN',
    flag: '🇲🇿',
    sign: 'MT',
    num: String(ISO_4217_CURRENCIES['MZN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['MZN'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  NAD: {
    country: 'Namibia',
    symbol: 'NAD',
    flag: '🇳🇦',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['NAD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['NAD'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['018'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  NGN: {
    country: 'Nigeria',
    symbol: 'NGN',
    flag: '🇳🇬',
    sign: '₦',
    num: String(ISO_4217_CURRENCIES['NGN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['NGN'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  NIO: {
    country: 'Nicaragua',
    symbol: 'NIO',
    flag: '🇳🇮',
    sign: 'C$',
    num: String(ISO_4217_CURRENCIES['NIO'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['NIO'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  NOK: {
    country: 'Norway',
    symbol: 'NOK',
    flag: '🇳🇴',
    sign: 'kr',
    num: String(ISO_4217_CURRENCIES['NOK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['NOK'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['154'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  NPR: {
    country: 'Nepal',
    symbol: 'NPR',
    flag: '🇳🇵',
    sign: '₨',
    num: String(ISO_4217_CURRENCIES['NPR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['NPR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  NZD: {
    country: 'New Zealand',
    symbol: 'NZD',
    flag: '🇳🇿',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['NZD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['NZD'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['053'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  OMR: {
    country: 'Oman',
    symbol: 'OMR',
    flag: '🇴🇲',
    sign: 'ر.ع.',
    num: String(ISO_4217_CURRENCIES['OMR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['OMR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  PAB: {
    country: 'Panama',
    symbol: 'PAB',
    flag: '🇵🇦',
    sign: 'B/.',
    num: String(ISO_4217_CURRENCIES['PAB'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PAB'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  PEN: {
    country: 'Peru',
    symbol: 'PEN',
    flag: '🇵🇪',
    sign: 'S/',
    num: String(ISO_4217_CURRENCIES['PEN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PEN'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  PGK: {
    country: 'Papua New Guinea',
    symbol: 'PGK',
    flag: '🇵🇬',
    sign: 'K',
    num: String(ISO_4217_CURRENCIES['PGK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PGK'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['054'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  PHP: {
    country: 'Philippines',
    symbol: 'PHP',
    flag: '🇵🇭',
    sign: '₱',
    num: String(ISO_4217_CURRENCIES['PHP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PHP'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  PKR: {
    country: 'Pakistan',
    symbol: 'PKR',
    flag: '🇵🇰',
    sign: '₨',
    num: String(ISO_4217_CURRENCIES['PKR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PKR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['034'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  PLN: {
    country: 'Poland',
    symbol: 'PLN',
    flag: '🇵🇱',
    sign: 'zł',
    num: String(ISO_4217_CURRENCIES['PLN'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PLN'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  PYG: {
    country: 'Paraguay',
    symbol: 'PYG',
    flag: '🇵🇾',
    sign: '₲',
    num: String(ISO_4217_CURRENCIES['PYG'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['PYG'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  QAR: {
    country: 'Qatar',
    symbol: 'QAR',
    flag: '🇶🇦',
    sign: 'ر.ق',
    num: String(ISO_4217_CURRENCIES['QAR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['QAR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  RON: {
    country: 'Romania',
    symbol: 'RON',
    flag: '🇷🇴',
    sign: 'lei',
    num: String(ISO_4217_CURRENCIES['RON'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['RON'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  RSD: {
    country: 'Serbia',
    symbol: 'RSD',
    flag: '🇷🇸',
    sign: 'дин',
    num: String(ISO_4217_CURRENCIES['RSD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['RSD'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['039'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  RUB: {
    country: 'Russian Federation',
    symbol: 'RUB',
    flag: '🇷🇺',
    sign: '₽',
    num: String(ISO_4217_CURRENCIES['RUB'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['RUB'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  RWF: {
    country: 'Rwanda',
    symbol: 'RWF',
    flag: '🇷🇼',
    sign: 'Fr',
    num: String(ISO_4217_CURRENCIES['RWF'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['RWF'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SAR: {
    country: 'Saudi Arabia',
    symbol: 'SAR',
    flag: '🇸🇦',
    sign: 'ر.س',
    num: String(ISO_4217_CURRENCIES['SAR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SAR'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SBD: {
    country: 'Solomon Islands',
    symbol: 'SBD',
    flag: '🇸🇧',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['SBD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SBD'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['054'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  SCR: {
    country: 'Seychelles',
    symbol: 'SCR',
    flag: '🇸🇨',
    sign: '₨',
    num: String(ISO_4217_CURRENCIES['SCR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SCR'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SDG: {
    country: 'Sudan',
    symbol: 'SDG',
    flag: '🇸🇩',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['SDG'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SDG'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['015'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SEK: {
    country: 'Sweden',
    symbol: 'SEK',
    flag: '🇸🇪',
    sign: 'kr',
    num: String(ISO_4217_CURRENCIES['SEK'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SEK'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['154'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SGD: {
    country: 'Singapore',
    symbol: 'SGD',
    flag: '🇸🇬',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['SGD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SGD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  SHP: {
    country: 'Saint Helena',
    symbol: 'SHP',
    flag: '🇸🇭',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['SHP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SHP'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['011'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SOS: {
    country: 'Somalia',
    symbol: 'SOS',
    flag: '🇸🇴',
    sign: 'Sh',
    num: String(ISO_4217_CURRENCIES['SOS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SOS'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SRD: {
    country: 'Suriname',
    symbol: 'SRD',
    flag: '🇸🇷',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['SRD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SRD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  SSP: {
    country: 'South Sudan',
    symbol: 'SSP',
    flag: '🇸🇸',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['SSP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SSP'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SVC: {
    country: 'El Salvador',
    symbol: 'SVC',
    flag: '🇸🇻',
    sign: '₡',
    num: String(ISO_4217_CURRENCIES['SVC'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SVC'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['013'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  SYP: {
    country: 'Syrian Arab Republic',
    symbol: 'SYP',
    flag: '🇸🇾',
    sign: '£',
    num: String(ISO_4217_CURRENCIES['SYP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SYP'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  SZL: {
    country: 'Eswatini',
    symbol: 'SZL',
    flag: '🇸🇿',
    sign: 'L',
    num: String(ISO_4217_CURRENCIES['SZL'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['SZL'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['018'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  THB: {
    country: 'Thailand',
    symbol: 'THB',
    flag: '🇹🇭',
    sign: '฿',
    num: String(ISO_4217_CURRENCIES['THB'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['THB'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  TJS: {
    country: 'Tajikistan',
    symbol: 'TJS',
    flag: '🇹🇯',
    sign: 'ЅМ',
    num: String(ISO_4217_CURRENCIES['TJS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TJS'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['143'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  TMT: {
    country: 'Turkmenistan',
    symbol: 'TMT',
    flag: '🇹🇲',
    sign: 'm',
    num: String(ISO_4217_CURRENCIES['TMT'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TMT'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['143'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  TND: {
    country: 'Tunisia',
    symbol: 'TND',
    flag: '🇹🇳',
    sign: 'د.ت',
    num: String(ISO_4217_CURRENCIES['TND'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TND'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['015'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  TOP: {
    country: 'Tonga',
    symbol: 'TOP',
    flag: '🇹🇴',
    sign: 'T$',
    num: String(ISO_4217_CURRENCIES['TOP'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TOP'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['061'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  TRY: {
    country: 'Turkey',
    symbol: 'TRY',
    flag: '🇹🇷',
    sign: '₺',
    num: String(ISO_4217_CURRENCIES['TRY'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TRY'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  TTD: {
    country: 'Trinidad and Tobago',
    symbol: 'TTD',
    flag: '🇹🇹',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['TTD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TTD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['029'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  TWD: {
    country: 'Taiwan',
    symbol: 'TWD',
    flag: '🇹🇼',
    sign: 'NT$',
    num: String(ISO_4217_CURRENCIES['TWD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TWD'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['030'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  TZS: {
    country: 'Tanzania',
    symbol: 'TZS',
    flag: '🇹🇿',
    sign: 'TSh',
    num: String(ISO_4217_CURRENCIES['TZS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['TZS'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  UAH: {
    country: 'Ukraine',
    symbol: 'UAH',
    flag: '🇺🇦',
    sign: '₴',
    num: String(ISO_4217_CURRENCIES['UAH'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['UAH'].digits,
    region: {
      regionCode: M49_REGIONS['150'].code,
      subregionCode: M49_SUBREGIONS['151'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  UGX: {
    country: 'Uganda',
    symbol: 'UGX',
    flag: '🇺🇬',
    sign: 'USh',
    num: String(ISO_4217_CURRENCIES['UGX'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['UGX'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  USD: {
    country: 'United States',
    symbol: 'USD',
    flag: '🇺🇸',
    sign: '$',
    num: String(ISO_4217_CURRENCIES['USD'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['USD'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['021'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[2],
    },
  },
  UYU: {
    country: 'Uruguay',
    symbol: 'UYU',
    flag: '🇺🇾',
    sign: '$U',
    num: String(ISO_4217_CURRENCIES['UYU'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['UYU'].digits,
    region: {
      regionCode: M49_REGIONS['019'].code,
      subregionCode: M49_SUBREGIONS['419'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['005'].code,
      businessRegion: BUSINESS_REGIONS[3],
    },
  },
  UZS: {
    country: 'Uzbekistan',
    symbol: 'UZS',
    flag: '🇺🇿',
    sign: "so'm",
    num: String(ISO_4217_CURRENCIES['UZS'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['UZS'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['143'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  VND: {
    country: 'Vietnam',
    symbol: 'VND',
    flag: '🇻🇳',
    sign: '₫',
    num: String(ISO_4217_CURRENCIES['VND'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['VND'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['035'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  VUV: {
    country: 'Vanuatu',
    symbol: 'VUV',
    flag: '🇻🇺',
    sign: 'VT',
    num: String(ISO_4217_CURRENCIES['VUV'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['VUV'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['054'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  WST: {
    country: 'Samoa',
    symbol: 'WST',
    flag: '🇼🇸',
    sign: 'WS$',
    num: String(ISO_4217_CURRENCIES['WST'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['WST'].digits,
    region: {
      regionCode: M49_REGIONS['009'].code,
      subregionCode: M49_SUBREGIONS['061'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[1],
    },
  },
  YER: {
    country: 'Yemen',
    symbol: 'YER',
    flag: '🇾🇪',
    sign: '﷼',
    num: String(ISO_4217_CURRENCIES['YER'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['YER'].digits,
    region: {
      regionCode: M49_REGIONS['142'].code,
      subregionCode: M49_SUBREGIONS['145'].code,
      intermediateRegionCode: null,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  ZAR: {
    country: 'South Africa',
    symbol: 'ZAR',
    flag: '🇿🇦',
    sign: 'R',
    num: String(ISO_4217_CURRENCIES['ZAR'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ZAR'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['018'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
  ZMW: {
    country: 'Zambia',
    symbol: 'ZMW',
    flag: '🇿🇲',
    sign: 'ZK',
    num: String(ISO_4217_CURRENCIES['ZMW'].number).padStart(3, '0'),
    d: ISO_4217_CURRENCIES['ZMW'].digits,
    region: {
      regionCode: M49_REGIONS['002'].code,
      subregionCode: M49_SUBREGIONS['202'].code,
      intermediateRegionCode: M49_INTERMEDIATE_REGIONS['014'].code,
      businessRegion: BUSINESS_REGIONS[0],
    },
  },
} as const;
