export const CURRENCIES = {
  AED: {
    country: 'United Arab Emirates',
    symbol: 'AED',
    flag: '🇦🇪',
    sign: 'د.إ',
  },
  AFN: { country: 'Afghanistan', symbol: 'AFN', flag: '🇦🇫', sign: '؋' },
  ALL: { country: 'Albania', symbol: 'ALL', flag: '🇦🇱', sign: 'L' },
  AMD: { country: 'Armenia', symbol: 'AMD', flag: '🇦🇲', sign: '֏' },
  AOA: { country: 'Angola', symbol: 'AOA', flag: '🇦🇴', sign: 'Kz' },
  ARS: { country: 'Argentina', symbol: 'ARS', flag: '🇦🇷', sign: '$' },
  AUD: { country: 'Australia', symbol: 'AUD', flag: '🇦🇺', sign: '$' },
  AWG: { country: 'Aruba', symbol: 'AWG', flag: '🇦🇼', sign: 'ƒ' },
  AZN: { country: 'Azerbaijan', symbol: 'AZN', flag: '🇦🇿', sign: '₼' },
  BAM: {
    country: 'Bosnia and Herzegovina',
    symbol: 'BAM',
    flag: '🇧🇦',
    sign: 'KM',
  },
  BBD: { country: 'Barbados', symbol: 'BBD', flag: '🇧🇧', sign: '$' },
  BDT: { country: 'Bangladesh', symbol: 'BDT', flag: '🇧🇩', sign: '৳' },
  BGN: { country: 'Bulgaria', symbol: 'BGN', flag: '🇧🇬', sign: 'лв' },
  BHD: { country: 'Bahrain', symbol: 'BHD', flag: '🇧🇭', sign: 'د.ب' },
  BIF: { country: 'Burundi', symbol: 'BIF', flag: '🇧🇮', sign: 'FBu' },
  BMD: { country: 'Bermuda', symbol: 'BMD', flag: '🇧🇲', sign: '$' },
  BND: { country: 'Brunei Darussalam', symbol: 'BND', flag: '🇧🇳', sign: '$' },
  BOB: {
    country: 'Bolivia, Plurinational State of',
    symbol: 'BOB',
    flag: '🇧🇴',
    sign: 'Bs',
  },
  BRL: { country: 'Brazil', symbol: 'BRL', flag: '🇧🇷', sign: 'R$' },
  BSD: { country: 'Bahamas', symbol: 'BSD', flag: '🇧🇸', sign: '$' },
  BTN: { country: 'Bhutan', symbol: 'BTN', flag: '🇧🇹', sign: 'Nu.' },
  BWP: { country: 'Botswana', symbol: 'BWP', flag: '🇧🇼', sign: 'P' },
  BYN: { country: 'Belarus', symbol: 'BYN', flag: '🇧🇾', sign: 'Br' },
  BZD: { country: 'Belize', symbol: 'BZD', flag: '🇧🇿', sign: '$' },
  CAD: { country: 'Canada', symbol: 'CAD', flag: '🇨🇦', sign: '$' },
  CDF: {
    country: 'Congo, The Democratic Republic of the',
    symbol: 'CDF',
    flag: '🇨🇩',
    sign: 'FC',
  },
  CHF: { country: 'Switzerland', symbol: 'CHF', flag: '🇨🇭', sign: 'Fr' },
  CLP: { country: 'Chile', symbol: 'CLP', flag: '🇨🇱', sign: '$' },
  CNY: { country: 'China', symbol: 'CNY', flag: '🇨🇳', sign: '¥' },
  COP: { country: 'Colombia', symbol: 'COP', flag: '🇨🇴', sign: '$' },
  CRC: { country: 'Costa Rica', symbol: 'CRC', flag: '🇨🇷', sign: '₡' },
  CUC: { country: 'Cuba', symbol: 'CUC', flag: '🇨🇺', sign: '$' },
  CVE: { country: 'Cabo Verde', symbol: 'CVE', flag: '🇨🇻', sign: 'Esc' },
  CZK: { country: 'Czechia', symbol: 'CZK', flag: '🇨🇿', sign: 'Kč' },
  DJF: { country: 'Djibouti', symbol: 'DJF', flag: '🇩🇯', sign: 'Fdj' },
  DKK: { country: 'Denmark', symbol: 'DKK', flag: '🇩🇰', sign: 'kr' },
  DOP: {
    country: 'Dominican Republic',
    symbol: 'DOP',
    flag: '🇩🇴',
    sign: 'RD$',
  },
  DZD: { country: 'Algeria', symbol: 'DZD', flag: '🇩🇿', sign: 'د.ج' },
  EGP: { country: 'Egypt', symbol: 'EGP', flag: '🇪🇬', sign: '£' },
  ERN: { country: 'Eritrea', symbol: 'ERN', flag: '🇪🇷', sign: 'Nkf' },
  ETB: { country: 'Ethiopia', symbol: 'ETB', flag: '🇪🇹', sign: 'Br' },
  EUR: { country: 'European Union', symbol: 'EUR', flag: '🇪🇺', sign: '€' },
  FJD: { country: 'Fiji', symbol: 'FJD', flag: '🇫🇯', sign: '$' },
  FKP: {
    country: 'Falkland Islands (Malvinas)',
    symbol: 'FKP',
    flag: '🇫🇰',
    sign: '£',
  },
  GBP: { country: 'United Kingdom', symbol: 'GBP', flag: '🇬🇧', sign: '£' },
  GEL: { country: 'Georgia', symbol: 'GEL', flag: '🇬🇪', sign: '₾' },
  GHS: { country: 'Ghana', symbol: 'GHS', flag: '🇬🇭', sign: '₵' },
  GIP: { country: 'Gibraltar', symbol: 'GIP', flag: '🇬🇮', sign: '£' },
  GMD: { country: 'Gambia', symbol: 'GMD', flag: '🇬🇲', sign: 'D' },
  GNF: { country: 'Guinea', symbol: 'GNF', flag: '🇬🇳', sign: 'FG' },
  GTQ: { country: 'Guatemala', symbol: 'GTQ', flag: '🇬🇹', sign: 'Q' },
  GYD: { country: 'Guyana', symbol: 'GYD', flag: '🇬🇾', sign: '$' },
  HKD: { country: 'Hong Kong', symbol: 'HKD', flag: '🇭🇰', sign: '$' },
  HNL: { country: 'Honduras', symbol: 'HNL', flag: '🇭🇳', sign: 'L' },
  HRK: { country: 'Croatia', symbol: 'HRK', flag: '🇭🇷', sign: 'kn' },
  HTG: { country: 'Haiti', symbol: 'HTG', flag: '🇭🇹', sign: 'G' },
  HUF: { country: 'Hungary', symbol: 'HUF', flag: '🇭🇺', sign: 'Ft' },
  IDR: { country: 'Indonesia', symbol: 'IDR', flag: '🇮🇩', sign: 'Rp' },
  ILS: { country: 'Israel', symbol: 'ILS', flag: '🇮🇱', sign: '₪' },
  INR: { country: 'India', symbol: 'INR', flag: '🇮🇳', sign: '₹' },
  IQD: { country: 'Iraq', symbol: 'IQD', flag: '🇮🇶', sign: 'ع.د' },
  IRR: { country: 'Iran', symbol: 'IRR', flag: '🇮🇷', sign: '﷼' },
  ISK: { country: 'Iceland', symbol: 'ISK', flag: '🇮🇸', sign: 'kr' },
  JMD: { country: 'Jamaica', symbol: 'JMD', flag: '🇯🇲', sign: '$' },
  JOD: { country: 'Jordan', symbol: 'JOD', flag: '🇯🇴', sign: 'د.أ' },
  JPY: { country: 'Japan', symbol: 'JPY', flag: '🇯🇵', sign: '¥' },
  KES: { country: 'Kenya', symbol: 'KES', flag: '🇰🇪', sign: 'KSh' },
  KGS: { country: 'Kyrgyzstan', symbol: 'KGS', flag: '🇰🇬', sign: '⃀' },
  KHR: { country: 'Cambodia', symbol: 'KHR', flag: '🇰🇭', sign: '៛' },
  KMF: { country: 'Comoros', symbol: 'KMF', flag: '🇰🇲', sign: 'Fr' },
  KPW: { country: 'North Korea', symbol: 'KPW', flag: '🇰🇵', sign: '₩' },
  KRW: { country: 'South Korea', symbol: 'KRW', flag: '🇰🇷', sign: '₩' },
  KWD: { country: 'Kuwait', symbol: 'KWD', flag: '🇰🇼', sign: 'د.ك' },
  KYD: { country: 'Cayman Islands', symbol: 'KYD', flag: '🇰🇾', sign: '$' },
  KZT: { country: 'Kazakhstan', symbol: 'KZT', flag: '🇰🇿', sign: '₸' },
  LAK: { country: 'Laos', symbol: 'LAK', flag: '🇱🇦', sign: '₭' },
  LBP: { country: 'Lebanon', symbol: 'LBP', flag: '🇱🇧', sign: 'ل.ل' },
  LKR: { country: 'Sri Lanka', symbol: 'LKR', flag: '🇱🇰', sign: 'Rs' },
  LRD: { country: 'Liberia', symbol: 'LRD', flag: '🇱🇷', sign: '$' },
  LSL: { country: 'Lesotho', symbol: 'LSL', flag: '🇱🇸', sign: 'L' },
  LYD: { country: 'Libya', symbol: 'LYD', flag: '🇱🇾', sign: 'ل.د' },
  MAD: { country: 'Morocco', symbol: 'MAD', flag: '🇲🇦', sign: 'د.م.' },
  MDL: { country: 'Moldova', symbol: 'MDL', flag: '🇲🇩', sign: 'L' },
  MGA: { country: 'Madagascar', symbol: 'MGA', flag: '🇲🇬', sign: 'Ar' },
  MKD: { country: 'North Macedonia', symbol: 'MKD', flag: '🇲🇰', sign: 'ден' },
  MMK: { country: 'Myanmar', symbol: 'MMK', flag: '🇲🇲', sign: 'K' },
  MNT: { country: 'Mongolia', symbol: 'MNT', flag: '🇲🇳', sign: '₮' },
  MOP: { country: 'Macao', symbol: 'MOP', flag: '🇲🇴', sign: 'MOP$' },
  MRO: { country: 'Mauritania', symbol: 'MRO', flag: '🇲🇷', sign: 'UM' },
  MUR: { country: 'Mauritius', symbol: 'MUR', flag: '🇲🇺', sign: '₨' },
  MVR: { country: 'Maldives', symbol: 'MVR', flag: '🇲🇻', sign: 'Rf' },
  MWK: { country: 'Malawi', symbol: 'MWK', flag: '🇲🇼', sign: 'MK' },
  MXN: { country: 'Mexico', symbol: 'MXN', flag: '🇲🇽', sign: '$' },
  MYR: { country: 'Malaysia', symbol: 'MYR', flag: '🇲🇾', sign: 'RM' },
  MZN: { country: 'Mozambique', symbol: 'MZN', flag: '🇲🇿', sign: 'MT' },
  NAD: { country: 'Namibia', symbol: 'NAD', flag: '🇳🇦', sign: '$' },
  NGN: { country: 'Nigeria', symbol: 'NGN', flag: '🇳🇬', sign: '₦' },
  NIO: { country: 'Nicaragua', symbol: 'NIO', flag: '🇳🇮', sign: 'C$' },
  NOK: { country: 'Norway', symbol: 'NOK', flag: '🇳🇴', sign: 'kr' },
  NPR: {
    country: 'Napri',
    symbol: 'NPR',
    flag: '🇳🇵',
    sign: '₨',
  },
  NZD: { country: 'New Zealand', symbol: 'NZD', flag: '🇳🇿', sign: '$' },
  OMR: { country: 'Oman', symbol: 'OMR', flag: '🇴🇲', sign: 'ر.ع.' },
  PAB: { country: 'Panama', symbol: 'PAB', flag: '🇵🇦', sign: 'B/.' },
  PEN: { country: 'Peru', symbol: 'PEN', flag: '🇵🇪', sign: 'S/' },
  PGK: { country: 'Papua New Guinea', symbol: 'PGK', flag: '🇵🇬', sign: 'K' },
  PHP: { country: 'Philippines', symbol: 'PHP', flag: '🇵🇭', sign: '₱' },
  PKR: { country: 'Pakistan', symbol: 'PKR', flag: '🇵🇰', sign: '₨' },
  PLN: { country: 'Poland', symbol: 'PLN', flag: '🇵🇱', sign: 'zł' },
  PYG: { country: 'Paraguay', symbol: 'PYG', flag: '🇵🇾', sign: '₲' },
  QAR: { country: 'Qatar', symbol: 'QAR', flag: '🇶🇦', sign: 'ر.ق' },
  RON: { country: 'Romania', symbol: 'RON', flag: '🇷🇴', sign: 'lei' },
  RSD: { country: 'Serbia', symbol: 'RSD', flag: '🇷🇸', sign: 'дин' },
  RUB: {
    country: 'Russian Federation',
    symbol: 'RUB',
    flag: '🇷🇺',
    sign: '₽',
  },
  RWF: { country: 'Rwanda', symbol: 'RWF', flag: '🇷🇼', sign: 'Fr' },
  SAR: { country: 'Saudi Arabia', symbol: 'SAR', flag: '🇸🇦', sign: 'ر.س' },
  SBD: { country: 'Solomon Islands', symbol: 'SBD', flag: '🇸🇧', sign: '$' },
  SCR: { country: 'Seychelles', symbol: 'SCR', flag: '🇸🇨', sign: '₨' },
  SDG: { country: 'Sudan', symbol: 'SDG', flag: '🇸🇩', sign: '£' },
  SEK: { country: 'Sweden', symbol: 'SEK', flag: '🇸🇪', sign: 'kr' },
  SGD: { country: 'Singapore', symbol: 'SGD', flag: '🇸🇬', sign: '$' },
  SHP: { country: 'Saint Helena', symbol: 'SHP', flag: '🇸🇭', sign: '£' },
  SLL: { country: 'Sierra Leone', symbol: 'SLL', flag: '🇸🇱', sign: 'Le' },
  SOS: { country: 'Somalia', symbol: 'SOS', flag: '🇸🇴', sign: 'Sh' },
  SRD: { country: 'Suriname', symbol: 'SRD', flag: '🇸🇷', sign: '$' },
  SSP: { country: 'South Sudan', symbol: 'SSP', flag: '🇸🇸', sign: '£' },
  STD: {
    country: 'Sao Tome and Principe',
    symbol: 'STD',
    flag: '🇸🇹',
    sign: 'Db',
  },
  SVC: { country: 'El Salvador', symbol: 'SVC', flag: '🇸🇻', sign: '₡' },
  SYP: {
    country: 'Syrian Arab Republic',
    symbol: 'SYP',
    flag: '🇸🇾',
    sign: '£',
  },
  SZL: { country: 'Eswatini', symbol: 'SZL', flag: '🇸🇿', sign: 'L' },
  THB: { country: 'Thailand', symbol: 'THB', flag: '🇹🇭', sign: '฿' },
  TJS: { country: 'Tajikistan', symbol: 'TJS', flag: '🇹🇯', sign: 'ЅМ' },
  TMT: { country: 'Turkmenistan', symbol: 'TMT', flag: '🇹🇲', sign: 'm' },
  TND: { country: 'Tunisia', symbol: 'TND', flag: '🇹🇳', sign: 'د.ت' },
  TOP: { country: 'Tonga', symbol: 'TOP', flag: '🇹🇴', sign: 'T$' },
  TRY: { country: 'Turkey', symbol: 'TRY', flag: '🇹🇷', sign: '₺' },
  TTD: {
    country: 'Trinidad and Tobago',
    symbol: 'TTD',
    flag: '🇹🇹',
    sign: '$',
  },
  TWD: { country: 'Taiwan', symbol: 'TWD', flag: '🇹🇼', sign: 'NT$' },
  TZS: { country: 'Tanzania', symbol: 'TZS', flag: '🇹🇿', sign: 'TSh' },
  UAH: { country: 'Ukraine', symbol: 'UAH', flag: '🇺🇦', sign: '₴' },
  UGX: { country: 'Uganda', symbol: 'UGX', flag: '🇺🇬', sign: 'USh' },
  USD: { country: 'United States', symbol: 'USD', flag: '🇺🇸', sign: '$' },
  UYU: { country: 'Uruguay', symbol: 'UYU', flag: '🇺🇾', sign: '$U' },
  UZS: { country: 'Uzbekistan', symbol: 'UZS', flag: '🇺🇿', sign: "so'm" },
  VEF: { country: 'Venezuela', symbol: 'VEF', flag: '🇻🇪', sign: 'Bs.' },
  VND: { country: 'Vietnam', symbol: 'VND', flag: '🇻🇳', sign: '₫' },
  VUV: { country: 'Vanuatu', symbol: 'VUV', flag: '🇻🇺', sign: 'VT' },
  WST: { country: 'Samoa', symbol: 'WST', flag: '🇼🇸', sign: 'WS$' },
  YER: { country: 'Yemen', symbol: 'YER', flag: '🇾🇪', sign: '﷼' },
  ZAR: { country: 'South Africa', symbol: 'ZAR', flag: '🇿🇦', sign: 'R' },
  ZMW: { country: 'Zambia', symbol: 'ZMW', flag: '🇿🇲', sign: 'ZK' },
  ZWL: { country: 'Zimbabwe', symbol: 'ZWL', flag: '🇿🇼', sign: 'Z$' },
} as const;
